### ISSUE TITLE
Error: array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by carlosvini** [mtownsend5512/remove-bg#2]
array_merge is being called here: https://github.com/mtownsend5512/remove-bg/blob/master/src/RemoveBg.php#L231

Version: mtownsend/remove-bg (1.2.0)

Code to reproduce:

```php
<?php

use Mtownsend\RemoveBg\RemoveBg;

$removebg = new RemoveBg(getenv('REMOVEBG_KEY'));
$removebg->file('/Users/bogus/foo.jpg')
    ->save('/Users/bogus/foo_'.uniqid().'.jpg');
```

It seems src/RemoveBg.php doesn't initialize $data at line 205 (https://github.com/mtownsend5512/remove-bg/blob/master/src/RemoveBg.php#L205).

The following change fixed it for me:

```php
    protected function formatBody()
    {
        switch ($this->imageFormat) {
            case 'image_file':
                $index = 0;
                $data = []; // <==== add this line
                foreach ($this->body as $key => $value) {
                    $data[$index]['name'] = $key;
                    $data[$index]['contents'] = $value;
                    $index++;
                }
                break;
            default:
                $data = $this->body;
        }
        return $data;
    }
```

Am I missing something or is it really a bug?

Thx

**Comment by mtownsend5512** [comment]
You're right, this is a bug. I just pushed a fix release. Update the package and utilize the new release to fix this issue.

Thanks for your issue!
