### ISSUE TITLE
Sending the fatal errors when credits ends in the account

### ISSUE THREAD

**Issue by amentotech006** [mtownsend5512/remove-bg#5]
Hello, Hope you are doing great

We have an issue, when have integrated the API into our project. During development we found an issue, our credits ends and it throw the errors while it should send errors in the response.

We have use below code to remove background 

`$removebg           = new RemoveBg($this->apiKey);
 $response            =  $removebg->file($image_url)->save($targetFile);`

![error](https://user-images.githubusercontent.com/85350704/120805297-1633f180-c55f-11eb-839a-5b60f49c9855.png)

It should send back the response, so we can show specific message to our users in case of credits goes to 0

Is there any solution for that ? 

Thanks

**Comment by psociety** [comment]
just add a try catch :S
Errors are expected to be thrown, not returned :o

**Comment by mtownsend5512** [comment]
Yes, you should wrap your code in a try/catch block to handle exceptions. It is the responsibility of the developer to handle exceptions that are thrown.
